# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/loco_nbdev',
                'doc_host': 'https://sangyu.github.io',
                'git_url': 'https://github.com/sangyu/loco_nbdev',
                'lib_path': 'loco_nbdev'},
  'syms': {'loco_nbdev.core': {'loco_nbdev.core.foo': ('core.html#foo', 'loco_nbdev/core.py')}}}