# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/loco_nbdev',
                'doc_host': 'https://sangyu.github.io',
                'git_url': 'https://github.com/sangyu/loco_nbdev',
                'lib_path': 'loco_nbdev'},
  'syms': { 'loco_nbdev.core': { 'loco_nbdev.core.correlationPlot': ('plottools.html#correlationplot', 'loco_nbdev/core.py'),
                                 'loco_nbdev.core.plotContrasts': ('plottools.html#plotcontrasts', 'loco_nbdev/core.py'),
                                 'loco_nbdev.core.saveDabestData': ('plottools.html#savedabestdata', 'loco_nbdev/core.py'),
                                 'loco_nbdev.core.savePlots': ('plottools.html#saveplots', 'loco_nbdev/core.py'),
                                 'loco_nbdev.core.setFont': ('plottools.html#setfont', 'loco_nbdev/core.py')}}}